version: "3"
services:
  mapbox-gl-indoor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 9966:9966
    volumes:
    - ./examples/simple-map.html:/mapbox-gl-indoor-plugin/index.html

