version: "3"
services:
  mapbox-gl-indoor:
    build:
      context: .
      dockerfile: Dockerfile
    image: indoor/mapbox-gl-indoor
    ports:
    - 8888:80
    volumes:
    - ./examples/index.html:/mapbox-gl-indoor/index.html

